upstream backserver {
    server backserver:8000;
}

upstream frontserver {
    server frontserver:3000;
}

server {
    listen 8080;
    http2 on;
    listen [::]:8080;
    server_name _;
    proxy_cache off;
    proxy_set_header Host $http_host; 
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_cache_bypass $http_upgrade;
    proxy_set_header x-ip-address $remote_addr;


    location /api/ {
        proxy_pass http://backserver;
    }


    location / {
        proxy_pass http://frontserver;
    }
}
